# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    environment: package
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps: 
    - uses: actions/checkout@v4 
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Display dotnet version
      run: dotnet --version
    - name: Install dependencies
      working-directory: ./ElkCreekServices.OpenScripts.Logging
      run: dotnet restore
    - name: Build
      working-directory: ./ElkCreekServices.OpenScripts.Logging
      run: dotnet build --configuration Release
    - name: Pack
      working-directory: ./ElkCreekServices.OpenScripts.Logging/ElkCreekServices.OpenScripts.Logging
      run: dotnet pack --configuration Release ElkCreekServices.OpenScripts.Logging.csproj
    - name: Push
      working-directory: ./ElkCreekServices.OpenScripts.Logging/ElkCreekServices.OpenScripts.Logging
      run: dotnet nuget push bin/Release/*.nupkg -k ${{ secrets.OPENLOG_PACKAGE_TOKEN }} --source "github"

